apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 10
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - image: gcr.io/cicd3334/gcpdevops-dev:latest
        name: gcp-devops-gke
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"

---

apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-dev
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: gcp
  type: LoadBalancer      